### ISSUE TITLE
Cannot boot DVD

### ISSUE THREAD

**Issue by jahshuah** [RedHatGov/ssg-el7-kickstart#1]
When attempting to boot the ssg-rhel-7.1.iso created via the `createiso.sh` script I receive the error: `Warning: /dev/root does not exist`.  After this, I'm dropped into the dracut emergency shell.  For reference, I'm installing in a Virtualbox VM to test prior to deployment, and using the latest RHEL 7.1 Server image.

**Comment by fcaviggia** [comment]
You might have got a previous bad version - I was working on some code to pull the RHEL version out of the iso image and that caused some issues with the initrd location. The code is fixed now - give it a `git pull` to the current version and test it out - let me know if that fixed your issue.
