### ISSUE TITLE
ssg-rhel-7.1.iso crashes VMWare Workstation

### ISSUE THREAD

**Issue by bkogami** [RedHatGov/ssg-el7-kickstart#4]
Hi,

I just tried creating the new ssg-rhel-7.1.iso using the command:
"createiso.sh rhel-server-7.1-x86_64-dvd.iso"
The new iso is created without any issue but if I try to create a new VM by using ssg-rhel-7.1.iso, it crashes the VMWorkstation. Also, If I burn it to a DVD (wodim -eject  -tao speed=0 dev=/dev/scd0 -v -data ssg-rhel-7.1.iso) and try to boot from this image, it does boot from this DVD.

Am I doing something wrong?

**Comment by fcaviggia** [comment]
Sorry about the delayed response - you might check that you have a valid SHA256 sum on the RHEL DVD. I've generally checked it on KVM/RHEV - but I can try it on VMware player when I get home. RHEL 7.2 is strongly recommended at this point.

**Comment by bkogami** [comment]
Thanks for getting back to me.
I downloaded RHEL 7.2 and verified the download using sha256sum.
I used the ./createiso.sh and it creates the iso image without any errors. I burn the iso image to a DVD and try to boot it from an HP z440 and it doesn't see the DVD as a bootable disk.

This has so much potential. I wish I could've used it. Bummer...

**Comment by fcaviggia** [comment]
Hmm. Does the unmodified RHEL 7.2 ISO image boot on that same system - I've used the images I make on Dell, HP, and Supermicro servers and several laptops so far. Also wondering if there is something in the bios preventing it booting to the ISO image. Have you tried directly dumping the image to a USB thumb drive (`dd if=ssg-rhel-7.2.iso of=/dev/sdc bs=1M` - assuming /dev/sdc is the thumb drive - get that from `dmesg`) - I've done that to boot from USB. Just some ideas to work around the issues....

**Comment by bkogami** [comment]
Yes. I burnt the unmodified RHEL 7.2 iso to a DVD and was able to boot and install Redhat 7 to my test system. I'll use the thumb drive approach if you think that would help. Just a little info. My physical test system is a UEFI system. The VM is setup using the bios.

**Comment by fcaviggia** [comment]
Added detection for UEFI BIOS to add partitioning for it. Please reopen issue if it is still a problem.

https://github.com/RedHatGov/ssg-el7-kickstart/commit/156a68b00a020f82a504d016d2218152b4b153ae
