### ISSUE TITLE
Could this be patched to run on CentOS 7?

### ISSUE THREAD

**Issue by darrynza** [RedHatGov/ssg-el7-kickstart#5]
anyone been able to fork this to run on CentOS7?

**Comment by fcaviggia** [comment]
I've been seriously thinking about porting the project over to CentOS/Scientific Linux 7.  Stay tuned...

**Comment by darrynza** [comment]
can't wait :) would be great to see

**Comment by fcaviggia** [comment]
I've done the initial work for the embedded kickstart - the SCAP Security Guide (SSG), the hardening script for this project, does not run in directly on CentOS - I'd have to fork the SSG bash scripts and do something similar to a previous effort that I developed here (Red Hat persuaded me to drop that in support of the SSG): 

       https://github.com/fcaviggia/hardening-script-el6

As there are a number of customers using CentOS as test platform - I might be persuaded to pick that back up for EL7 since SSG does not contain the CPE and OVAL definitions to harden CentOS/Scientific Linux... this effort would be on my personal site rather than the redhatgov group though.

**Comment by defpoint** [comment]
Definitely let us know -- we've been using the ssg-el7 scripts here as a base for a fork that runs on CentOS for the last few months (and using that as baseline to build up esxi vms and AMIs, etc...) -- we'd be happy to participate in a CentOS focused effort!

**Comment by fcaviggia** [comment]
I'm in the process of normalizing the SSG scripts into a common set of bash scripts with a configuration to set variables and scripts off and on (that way you can customize the scripts with a profile, roll it as an RPM, and deploy to your systems) or possibly  SSH for centralized management as well... It's all free time effort for me - I have to pay the bills first.

**Comment by defpoint** [comment]
I hear that! I'll keep an eye out to see if a repo pops up on your personal site -- I think this would be super useful to lots of people out in AWS land that want to use the CentOS marketplace AMIs, etc..

**Comment by fcaviggia** [comment]
No need to fork the SSG - I've modified the existing RHEL 7 SSG CPE and OVAL definitions with the following script:

#!/bin/bash
sed -i -e "s#<platform>Red Hat Enterprise Linux 7</platform>#<platform>CentOS 7</platform>##g" /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
sed -i -e "s#cpe:/o:redhat:enterprise_linux:7#cpe:/o:centos:centos:7##g" /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
sed -i -e "s#cpe:/o:redhat:enterprise_linux#cpe:/o:centos:centos##g" /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
scap xccdf eval --profile stig-rhel7-server-upstream --remediate --cpe /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

**Comment by darrynza** [comment]
Sir you are a legend.

On Mon, Feb 8, 2016 at 5:32 AM, Frank Caviggia <notifications@github.com>
wrote:

> No need to fork the SSG - I've modified the existing RHEL 7 SSG CPE and
> OVAL definitions with the following script:
>
> #!/bin/bash
> sed -i -e "s#Red Hat Enterprise Linux 7#CentOS 7##g"
> /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
> sed -i -e "s#cpe:/o:redhat:enterprise_linux:7#cpe:/o:centos:centos:7##g"
> /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
> sed -i -e "s#cpe:/o:redhat:enterprise_linux#cpe:/o:centos:centos##g"
> /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
> scap xccdf eval --profile stig-rhel7-server-upstream --remediate --cpe
> /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml
> /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedHatGov/ssg-el7-kickstart/issues/5#issuecomment-181181280>
> .
>



-- 
Darryn Francesco
Mobile: +27780406286
Email: darryn.francesco@gmail.com
Linkdin: http://za.linkedin.com/pub/darryn-francesco/16/531/979

**Comment by fcaviggia** [comment]
All while watching the super bowl... :)

**Comment by shawndwells** [comment]
Note this change was made in upstream SSG several months ago. SSG supports
RHEL, Scientific, OEL, CentOS, and most recently, Debian content was added.

Strongly advise rebasing upstream.


On Feb 7, 2016, at 10:33 PM, Frank Caviggia <notifications@github.com>
wrote:

No need to fork the SSG - I've modified the existing RHEL 7 SSG CPE and
OVAL definitions with the following script:

#!/bin/bash
sed -i -e "s#Red Hat Enterprise Linux 7#CentOS 7##g"
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
sed -i -e "s#cpe:/o:redhat:enterprise_linux:7#cpe:/o:centos:centos:7##g"
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
sed -i -e "s#cpe:/o:redhat:enterprise_linux#cpe:/o:centos:centos##g"
/usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
scap xccdf eval --profile stig-rhel7-server-upstream --remediate --cpe
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

—
Reply to this email directly or view it on GitHub
<https://github.com/RedHatGov/ssg-el7-kickstart/issues/5#issuecomment-181181280>
.

**Comment by fcaviggia** [comment]
I was able to integrate the upstream SSG into the CentOS 7 build - I should have a repository up on my personal page after some additional unit testing...

**Comment by fcaviggia** [comment]
https://github.com/fcaviggia/hardened-centos7-kickstart/

**Comment by fcaviggia** [comment]
Marking this discussion as closed.
