### ISSUE TITLE
audit_rules_privileged_commands fails

### ISSUE THREAD

**Issue by pysysops** [RedHatGov/ssg-el7-kickstart#52]
Hi!

Currently an OpenSCAP scan rule fails when using the audit rules produced by `ssg-supplemental.sh`. I believe it's because of the way that the scap-security-guide checks the file:  

https://github.com/OpenSCAP/scap-security-guide/blob/0f098e5ff5935e74fbb6a56ec03f4bdb5c90ccdd/shared/oval/audit_rules_privileged_commands.xml#L78

I've fixed this tested and fixed this locally and will open a PR now :unicorn:

**Comment by stephenwb** [comment]
Please see my comments in PR #51 (https://github.com/RedHatGov/ssg-el7-kickstart/pull/51#pullrequestreview-40395379)
I assert that the logic of the check in the SSG should be fixed, not the audit rules created by `ssg-supplemental.sh`

**Comment by pysysops** [comment]
I agree. Hardcoded auid is not a great thing. In fact someone else has come across this and raised it. 

https://github.com/OpenSCAP/scap-security-guide/issues/2017

I'll return back to the original fix.

Thanks 😄

**Comment by pysysops** [comment]
Closing due to explanation from @stephenwb regarding the audit rules discussed in PR #46
