### ISSUE TITLE
Banner Message Text

### ISSUE THREAD

**Issue by david-paige-ctr** [RedHatGov/ssg-el7-kickstart#54]
The banner message text in the ssg-supplemental.sh script is incorrect.  This is the line which contains the error:

-This IS includes security measures (e.g., authentication and access controls) \nto protect USG interests -- not for your personal benefit or privacy.

There are no spaces around the double-dash.  A common error is to put spaces there.  The text is correct at this link, which should be publically accessible. 
https://iase.disa.mil/Documents/unclass-consent_banner.zip

**Comment by fcaviggia** [comment]
Most people replace that anyway, every government group I work with generally has their own Banner - I just matched it with the SCAP Security Guide version. You are welcome to change it for your own use, but you might submit that as a bug to the upstream SCAP Security Guide (https://github.com/OpenSCAP/scap-security-guide/)
