### ISSUE TITLE
Change Licence (GPLv2 -> APL2.0)

### ISSUE THREAD

**Issue by fcaviggia** [RedHatGov/ssg-el7-kickstart#61]
I would like to change the Licence of this project from GNU Public Licence version 2 (GPLv2) to Apache Public Licence  2.0 (APL2.0) to allow people to utilize this software without having to submit changes back to the project.  I believe that this will allow for better use in the DOD/IC without the requirements to give back everything - however, it would still remain open source as a reference model.

**Comment by fcaviggia** [comment]
Comments? Questions?

**Comment by shawndwells** [comment]
Hey Frank, I've been on PTO for the past two weeks. Note sure if this went anywhere.

In general, I don't think anyone would mind if the license swaps.

An underlying question is why this is a problem. What problem is trying to be solved?

**Comment by fcaviggia** [comment]
GPLv2 requires people to submit code back - a more permissive Licence was suggested to allow people to use as is with out having to submit changes back, allowing for better integration with government projects - it's the same licence that NSA/SMIP was released under.

**Comment by aclater** [comment]
I'm not quite certain that interpretation of GPLv2 is correct.

https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#GPLRequireSourcePostedPublic

ac

**Comment by fcaviggia** [comment]
I'd prefer a more permissive licence rather than a copyleft licence, especially for this project.

**Comment by shawndwells** [comment]
The underlying concern does not appear to be addressed, but feel free to switch the licenses over (you wrote the code!).
