### ISSUE TITLE
Header & Footer label displays do not display correctly

### ISSUE THREAD

**Issue by lkkevin** [RedHatGov/ssg-el7-kickstart#65]
Hi, i created and installed the rhel 7.4 iso using this lockdown scrtipt.  The header and footer display:
<span font_family='libera                            <span font_family='liberation-sans' weight='bold' foreground='#FFFFF' size='small'>TOP SECRET//SCI</span> 

Could you help me to correct this issue.  Thanks.

**Comment by lkkevin** [comment]
I found a problem.  On meny.py, line 1016, a color code is missing an F:  f.write('fgcolor = "#FFFFF"\n')
it should be: f.write('fgcolor = "#FFFFFF"\n')

**Comment by lkkevin** [comment]
I found a problem. On meny.py, line 1016, a color code is missing an F: f.write('fgcolor = "#FFFFF"\n')
it should be: f.write('fgcolor = "#FFFFFF"\n')

**Comment by fcaviggia** [comment]
Thanks. Is this still an issue? I've been out of it with a new baby and travel.

**Comment by lkkevin** [comment]
Issue resolved. Congrat on a new baby.  May you be filled with joy and happiness with the arrival of your new baby.  Wishing your new family all the absolute best.
