### ISSUE TITLE
is there any change for RHEL 7.7

### ISSUE THREAD

**Issue by jadwani** [RedHatGov/ssg-el7-kickstart#73]
Hi, Is there any change for RHEL latest version released (7.7).

**Comment by fcaviggia** [comment]
I'll give it a look this weekend.  I've been pretty swamped with other projects.

**Comment by fcaviggia** [comment]
I downloaded RHEL 7.7 - I'm still working on it.

**Comment by fcaviggia** [comment]
Give the updates a shot - let me know if they work.

**Comment by jadwani** [comment]
Thank you I will try it.

**Comment by jmaughmer** [comment]
I run a modified version of this and didn't have to make any changes for RHEL 7.7.

**Comment by fcaviggia** [comment]
I noticed the scap-security-guide wasn't installing on RHEL 7.7 - so that was an issue for running the hardening script. I'm revamping the entire thing for RHEL 8 - but I might release that work under MITRE since I'm employed by them.

**Comment by jmaughmer** [comment]
I didn't have the issue with OpenSCAP as I removed the RPMs and use the ones provided in the 7.6/7.7 ISO. The Nessus scans were coming back good.

**Comment by stephenwb** [comment]
@fcaviggia if you decide to change the location/owner of this project for the RHEL8 version, please do something to announce where it can be found

**Comment by fcaviggia** [comment]
I'm developing it on the side - 8.1 is supposed to get Common Criteria certification (a requirement for NIAP)
